### ISSUE TITLE
Practica_de_Hilos

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-de-hilos-Abraham890#2]
[Abraham_Reyes_Ortiz_Reporte_de_ Practica_de_Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Abraham890/files/6498515/Abraham_Reyes_Ortiz_Reporte_de_.Practica_de_Hilos.pdf)

**Comment by Eva155** [comment]
20 PUNTOS
CALIFICÓ: EVA AGUILAR AVENDAÑO

**Comment by josealfredo79** [comment]
bien hecho y revisado
